import HolidaysSearchForm from './HolidaysSearchForm';
import Link from 'next/link';
//The tailwind styling here was generated by ChatGPT to allow for beautiful styling
export default function HolidaysPage() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-b from-gray-900 to-gray-800 text-white px-4">
      <div className="w-full max-w-2xl space-y-6 text-center">
        <div className="space-y-2">
          <h1 className="text-4xl font-extrabold">🌎 Global Holiday Finder</h1>
          <p className="text-gray-300 text-lg">
            Select a country and date to discover what holidays are being celebrated around the world.
          </p>
          <Link
            href="/about"
            className="inline-block mt-2 text-blue-400 hover:text-blue-300 underline transition"
          >
            Learn more about this project →
          </Link>
        </div>
        <HolidaysSearchForm />
      </div>
    </main>
  );
}
